# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/RV_sim/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/RV_sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/RV_sim/CMakeFiles /home/alex/RV_sim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/RV_sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cosim

# Build rule for target.
cosim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cosim
.PHONY : cosim

# fast build rule for target.
cosim/fast:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/build
.PHONY : cosim/fast

#=============================================================================
# Target rules for targets named fsim

# Build rule for target.
fsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fsim
.PHONY : fsim

# fast build rule for target.
fsim/fast:
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/build
.PHONY : fsim/fast

#=============================================================================
# Target rules for targets named tsim

# Build rule for target.
tsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tsim
.PHONY : tsim

# fast build rule for target.
tsim/fast:
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/build
.PHONY : tsim/fast

cosim.o: cosim.cpp.o

.PHONY : cosim.o

# target to build an object file
cosim.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosim.cpp.o
.PHONY : cosim.cpp.o

cosim.i: cosim.cpp.i

.PHONY : cosim.i

# target to preprocess a source file
cosim.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosim.cpp.i
.PHONY : cosim.cpp.i

cosim.s: cosim.cpp.s

.PHONY : cosim.s

# target to generate assembly for a file
cosim.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosim.cpp.s
.PHONY : cosim.cpp.s

cosimulator.o: cosimulator.cpp.o

.PHONY : cosimulator.o

# target to build an object file
cosimulator.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosimulator.cpp.o
.PHONY : cosimulator.cpp.o

cosimulator.i: cosimulator.cpp.i

.PHONY : cosimulator.i

# target to preprocess a source file
cosimulator.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosimulator.cpp.i
.PHONY : cosimulator.cpp.i

cosimulator.s: cosimulator.cpp.s

.PHONY : cosimulator.s

# target to generate assembly for a file
cosimulator.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/cosimulator.cpp.s
.PHONY : cosimulator.cpp.s

decoder.o: decoder.cpp.o

.PHONY : decoder.o

# target to build an object file
decoder.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/decoder.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/decoder.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/decoder.cpp.o
.PHONY : decoder.cpp.o

decoder.i: decoder.cpp.i

.PHONY : decoder.i

# target to preprocess a source file
decoder.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/decoder.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/decoder.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/decoder.cpp.i
.PHONY : decoder.cpp.i

decoder.s: decoder.cpp.s

.PHONY : decoder.s

# target to generate assembly for a file
decoder.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/decoder.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/decoder.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/decoder.cpp.s
.PHONY : decoder.cpp.s

fsim.o: fsim.cpp.o

.PHONY : fsim.o

# target to build an object file
fsim.cpp.o:
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/fsim.cpp.o
.PHONY : fsim.cpp.o

fsim.i: fsim.cpp.i

.PHONY : fsim.i

# target to preprocess a source file
fsim.cpp.i:
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/fsim.cpp.i
.PHONY : fsim.cpp.i

fsim.s: fsim.cpp.s

.PHONY : fsim.s

# target to generate assembly for a file
fsim.cpp.s:
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/fsim.cpp.s
.PHONY : fsim.cpp.s

instruction.o: instruction.cpp.o

.PHONY : instruction.o

# target to build an object file
instruction.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/instruction.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/instruction.cpp.o
.PHONY : instruction.cpp.o

instruction.i: instruction.cpp.i

.PHONY : instruction.i

# target to preprocess a source file
instruction.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/instruction.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/instruction.cpp.i
.PHONY : instruction.cpp.i

instruction.s: instruction.cpp.s

.PHONY : instruction.s

# target to generate assembly for a file
instruction.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/instruction.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/instruction.cpp.s
.PHONY : instruction.cpp.s

memory.o: memory.cpp.o

.PHONY : memory.o

# target to build an object file
memory.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/memory.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/memory.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/memory.cpp.o
.PHONY : memory.cpp.o

memory.i: memory.cpp.i

.PHONY : memory.i

# target to preprocess a source file
memory.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/memory.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/memory.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/memory.cpp.i
.PHONY : memory.cpp.i

memory.s: memory.cpp.s

.PHONY : memory.s

# target to generate assembly for a file
memory.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/memory.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/memory.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/memory.cpp.s
.PHONY : memory.cpp.s

proc_state.o: proc_state.cpp.o

.PHONY : proc_state.o

# target to build an object file
proc_state.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/proc_state.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/proc_state.cpp.o
.PHONY : proc_state.cpp.o

proc_state.i: proc_state.cpp.i

.PHONY : proc_state.i

# target to preprocess a source file
proc_state.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/proc_state.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/proc_state.cpp.i
.PHONY : proc_state.cpp.i

proc_state.s: proc_state.cpp.s

.PHONY : proc_state.s

# target to generate assembly for a file
proc_state.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/proc_state.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/proc_state.cpp.s
.PHONY : proc_state.cpp.s

simulator.o: simulator.cpp.o

.PHONY : simulator.o

# target to build an object file
simulator.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/simulator.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/simulator.cpp.o
.PHONY : simulator.cpp.o

simulator.i: simulator.cpp.i

.PHONY : simulator.i

# target to preprocess a source file
simulator.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/simulator.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/simulator.cpp.i
.PHONY : simulator.cpp.i

simulator.s: simulator.cpp.s

.PHONY : simulator.s

# target to generate assembly for a file
simulator.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/simulator.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/simulator.cpp.s
.PHONY : simulator.cpp.s

tinstruction.o: tinstruction.cpp.o

.PHONY : tinstruction.o

# target to build an object file
tinstruction.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tinstruction.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tinstruction.cpp.o
.PHONY : tinstruction.cpp.o

tinstruction.i: tinstruction.cpp.i

.PHONY : tinstruction.i

# target to preprocess a source file
tinstruction.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tinstruction.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tinstruction.cpp.i
.PHONY : tinstruction.cpp.i

tinstruction.s: tinstruction.cpp.s

.PHONY : tinstruction.s

# target to generate assembly for a file
tinstruction.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tinstruction.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tinstruction.cpp.s
.PHONY : tinstruction.cpp.s

tproc_state.o: tproc_state.cpp.o

.PHONY : tproc_state.o

# target to build an object file
tproc_state.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tproc_state.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tproc_state.cpp.o
.PHONY : tproc_state.cpp.o

tproc_state.i: tproc_state.cpp.i

.PHONY : tproc_state.i

# target to preprocess a source file
tproc_state.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tproc_state.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tproc_state.cpp.i
.PHONY : tproc_state.cpp.i

tproc_state.s: tproc_state.cpp.s

.PHONY : tproc_state.s

# target to generate assembly for a file
tproc_state.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tproc_state.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tproc_state.cpp.s
.PHONY : tproc_state.cpp.s

tsim.o: tsim.cpp.o

.PHONY : tsim.o

# target to build an object file
tsim.cpp.o:
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsim.cpp.o
.PHONY : tsim.cpp.o

tsim.i: tsim.cpp.i

.PHONY : tsim.i

# target to preprocess a source file
tsim.cpp.i:
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsim.cpp.i
.PHONY : tsim.cpp.i

tsim.s: tsim.cpp.s

.PHONY : tsim.s

# target to generate assembly for a file
tsim.cpp.s:
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsim.cpp.s
.PHONY : tsim.cpp.s

tsimulator.o: tsimulator.cpp.o

.PHONY : tsimulator.o

# target to build an object file
tsimulator.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tsimulator.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsimulator.cpp.o
.PHONY : tsimulator.cpp.o

tsimulator.i: tsimulator.cpp.i

.PHONY : tsimulator.i

# target to preprocess a source file
tsimulator.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tsimulator.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsimulator.cpp.i
.PHONY : tsimulator.cpp.i

tsimulator.s: tsimulator.cpp.s

.PHONY : tsimulator.s

# target to generate assembly for a file
tsimulator.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/tsimulator.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/tsimulator.cpp.s
.PHONY : tsimulator.cpp.s

vmemory.o: vmemory.cpp.o

.PHONY : vmemory.o

# target to build an object file
vmemory.cpp.o:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/vmemory.cpp.o
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/vmemory.cpp.o
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/vmemory.cpp.o
.PHONY : vmemory.cpp.o

vmemory.i: vmemory.cpp.i

.PHONY : vmemory.i

# target to preprocess a source file
vmemory.cpp.i:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/vmemory.cpp.i
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/vmemory.cpp.i
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/vmemory.cpp.i
.PHONY : vmemory.cpp.i

vmemory.s: vmemory.cpp.s

.PHONY : vmemory.s

# target to generate assembly for a file
vmemory.cpp.s:
	$(MAKE) -f CMakeFiles/cosim.dir/build.make CMakeFiles/cosim.dir/vmemory.cpp.s
	$(MAKE) -f CMakeFiles/fsim.dir/build.make CMakeFiles/fsim.dir/vmemory.cpp.s
	$(MAKE) -f CMakeFiles/tsim.dir/build.make CMakeFiles/tsim.dir/vmemory.cpp.s
.PHONY : vmemory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cosim"
	@echo "... fsim"
	@echo "... tsim"
	@echo "... cosim.o"
	@echo "... cosim.i"
	@echo "... cosim.s"
	@echo "... cosimulator.o"
	@echo "... cosimulator.i"
	@echo "... cosimulator.s"
	@echo "... decoder.o"
	@echo "... decoder.i"
	@echo "... decoder.s"
	@echo "... fsim.o"
	@echo "... fsim.i"
	@echo "... fsim.s"
	@echo "... instruction.o"
	@echo "... instruction.i"
	@echo "... instruction.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... proc_state.o"
	@echo "... proc_state.i"
	@echo "... proc_state.s"
	@echo "... simulator.o"
	@echo "... simulator.i"
	@echo "... simulator.s"
	@echo "... tinstruction.o"
	@echo "... tinstruction.i"
	@echo "... tinstruction.s"
	@echo "... tproc_state.o"
	@echo "... tproc_state.i"
	@echo "... tproc_state.s"
	@echo "... tsim.o"
	@echo "... tsim.i"
	@echo "... tsim.s"
	@echo "... tsimulator.o"
	@echo "... tsimulator.i"
	@echo "... tsimulator.s"
	@echo "... vmemory.o"
	@echo "... vmemory.i"
	@echo "... vmemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

